services:
  mysql_db:
    image: mysql:8.0 
    container_name: my-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password 
      MYSQL_DATABASE: controle_ponto 
      MYSQL_USER: myuser 
      MYSQL_PASSWORD: mypassword 
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql 

volumes:
  mysql_data: